#logging:
#  level:
#    org.hibernate: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: sa # it was added for fix generation table for entity
    url: jdbc:h2:~/Desktop/Learning/h2db
